### ISSUE TITLE
unable to start game.

### ISSUE THREAD

**Issue by Astrydax** [DavidGriffith/frotz#50]
Loaded Game: zork
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn dfrotz ENOENT
    at _errnoException (util.js:1021:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Astrydax** [comment]
wrong repo, sorry
